# baixa.py

from enum import Enum


class Baixa(Enum):
    ACERTOS = "ACERTOS"
    PROTESTADO = "PROTESTADO"
    DEVOLUCAO = "DEVOLUCAO"
    PROTESTOAPOSBAIXA = "PROTESTOAPOSBAIXA"
    PAGODIRETOAOCLIENTE = "PAGODIRETOAOCLIENTE"
    SUBISTITUICAO = "SUBISTITUICAO"
    FALTADESOLUCAO = "FALTADESOLUCAO"
    APEDIDODOCLIENTE = "APEDIDODOCLIENTE"
