# status_pagamento.py

from enum import Enum


class StatusPagamento(Enum):
    EMPROCESSAMENTO = "EMPROCESSAMENTO"
    AGENDADO_CANCELADO = "AGENDADO_CANCELADO"
    AGUARDANDO_APROVACAO = "AGUARDANDO_APROVACAO"
    APROVADO = "APROVADO"
    CANCELADO = "CANCELADO"
    AGENDADO = "AGENDADO"
    REALIZADO = "REALIZADO"
    ERRO = "ERRO"
    APROVACAO_EXPIRADA = "APROVACAO_EXPIRADA"
    REPROVADO = "REPROVADO"
    NAO_COMPENSADO = "NAO_COMPENSADO"
