# status_transacao_pix.py

from enum import Enum


class StatusTransacaoPix(Enum):
    CRIADO = "CRIADO"
    AGUARDANDO_APROVACAO = "AGUARDANDO_APROVACAO"
    APROVADO = "APROVADO"
    REPROVADO = "REPROVADO"
    EXPIRADO = "EXPIRADO"
    CANCELADO = "CANCELADO"
    FALHA = "FALHA"
    AGENDADO = "AGENDADO"
    PAGO = "PAGO"
    ENVIADO = "ENVIADO"
    CANCELADO_SEM_SALDO = "CANCELADO_SEM_SALDO"
    DEBITADO = "DEBITADO"
    PARCIALMENTE_DEBITADO = "PARCIALMENTE_DEBITADO"
    PARCIALMENTE_PAGO = "PARCIALMENTE_PAGO"
    NAO_DEBITADO = "NAO_DEBITADO"
    AGENDAMENTO_CANCELADO = "AGENDAMENTO_CANCELADO"
