# tipo_transacao.py

from enum import Enum


class TipoTransacao(Enum):
    DEBITO_EM_CONTA = "DEBITO_EM_CONTA"
    DEPOSITO_BOLETO = "DEPOSITO_BOLETO"
    ANTECIPACAO_RECEBIVEIS = "ANTECIPACAO_RECEBIVEIS"
    ANTECIPACAO_RECEBIVEIS_CARTAO = "ANTECIPACAO_RECEBIVEIS_CARTAO"
    BOLETO_COBRANCA = "BOLETO_COBRANCA"
    CAMBIO = "CAMBIO"
    CASHBACK = "CASHBACK"
    CHEQUE = "CHEQUE"
    ESTORNO = "ESTORNO"
    DOMICILIO_CARTAO = "DOMICILIO_CARTAO"
    FINANCIAMENTO = "FINANCIAMENTO"
    IMPOSTO = "IMPOSTO"
    INTERPAG = "INTERPAG"
    INVESTIMENTO = "INVESTIMENTO"
    JUROS = "JUROS"
    MAQUININHA_GRANITO = "MAQUININHA_GRANITO"
    MULTA = "MULTA"
    OUTROS = "OUTROS"
    PAGAMENTO = "PAGAMENTO"
    PIX = "PIX"
    PROVENTOS = "PROVENTOS"
    SAQUE = "SAQUE"
    COMPRA_DEBITO = "COMPRA_DEBITO"
    DEBITO_AUTOMATICO = "DEBITO_AUTOMATICO"
    TARIFA = "TARIFA"
    TRANSFERENCIA = "TRANSFERENCIA"
